pipeline {
agent any 
stages {
    stage('remove old container') {
        steps {
            script{
                def containerName = "frontend"
                def checkContainer = sh(script: "docker ps -a --format '{{.Names}}' | grep -w ${containerName}", returnStatus: true)
                if (checkContainer == 0){
                    echo "container ${containerName} exists. removing...."
                    sh "docker container rm -f ${containerName}"
                } else {
                    echo "Container ${containerName} does not exist. Skipping removeal..."
                }
            }
      }
    }
    stage('Image Build') {
        steps {
           sh 'cd webapp && docker build -t web .'
      }
    }
    stage('Running Container') {
        steps {
           sh 'docker container run -dt --name frontend --network lmsnetwork -p 80:80 web'
      }
    }
    stage('build status') {
        steps {
           sh 'echo backend deployed'
      }
    }
  }
}
